### ISSUE TITLE
"and more"?  What are all the languages it's trained on?

### ISSUE THREAD

**Issue by rossburnett** [ibm-granite/watsonx-code-assistant-individual#1]
Please list all the languages that Granite is trained in.  I am specifically wondering if one of the most used languages, COBOL, is supported.

**Comment by alvkhtan** [comment]
The Granite code model has been trained on data encompassing 116 programming languages (see Appendix A in the [Granite technical paper](https://github.com/ibm-granite/granite-code-models)), although its performance may vary across these languages depending on the depth and breadth of the data available for each.

**Comment by rossburnett** [comment]
Hi,

Thanks for the reply.  I couldn’t find the Appendix, but if it has been trained in 116 languages, I have to assume COBOL was one of them.

**Comment by alvkhtan** [comment]
page 28: https://arxiv.org/pdf/2405.04324

note: performance vary across these languages depending on the depth and breadth of the data available for each

**Comment by alvkhtan** [comment]
@rossburnett hope the above answers your question

**Comment by rossburnett** [comment]
@alvkhtan Yes, it does, thanks.  I'll have to see what it "thinks" of my code.
