### ISSUE TITLE
Ollama is not running in your IDE

### ISSUE THREAD

**Issue by mgorjis** [ibm-granite/watsonx-code-assistant-individual#3]
Installed the model locally via Ollama, and ran the `ollama serve` successfully in the command line.
but keep seeing `Ollama is not running in your IDE` error on VScode and chat/other functionalities are disabled

<img width="680" alt="image" src="https://github.com/user-attachments/assets/063c82db-534d-4088-b2ee-6931265d0b32">

**Comment by alvkhtan** [comment]
Hi @mgorjis , let us know if you have gotten past this issue after removing the conflicting extension in your vscode, thanks .

**Comment by mgorjis** [comment]
.
