### ISSUE TITLE
Windows silent mode install of ollama

### ISSUE THREAD

**Issue by jamescho72** [ibm-granite/watsonx-code-assistant-individual#5]
**Description:**
Test and script ollama install for windows using 
OllamaSetup.exe /Silent

Allow a common experience of installer across windows, mac, linux.

**Comment by chetan-hireholi** [comment]
Thank you @jamescho72 for the feedback. Ollama installer has a similar experience for package installation.
I have hidden the `brew install` commands for now so as not to make the installation process complicated by introducing different installation instructions.
